# Generated by Django 4.1.5 on 2023-02-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.TextField()),
                ('rfc', models.CharField(max_length=20)),
                ('calle_numero_colonia', models.TextField()),
                ('ciudad', models.TextField()),
                ('estado', models.TextField()),
                ('cp', models.IntegerField()),
                ('contacto', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
