# Generated by Django 4.1.5 on 2023-03-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_libre_servicio_empleado_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('concepto', models.TextField()),
                ('notas', models.TextField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=16)),
                ('version_original', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=1)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cotizacion')),
            ],
            options={
                'verbose_name': 'Libre',
                'verbose_name_plural': 'Libres',
            },
        ),
        migrations.DeleteModel(
            name='Libre',
        ),
        migrations.AddField(
            model_name='servicio',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='servicio',
            name='cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.cotizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='version_original',
            field=models.IntegerField(default=1),
        ),
    ]
