# Generated by Django 4.1.5 on 2023-03-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_servicio_acreditado_servicio_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
