# Generated by Django 4.1.5 on 2023-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_cotizacion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
