# Generated by Django 4.2 on 2023-04-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_cliente_activo_empleado_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('ver_clientes', 'Ver Clientes'), ('ver_cotizaciones', 'Ver Cotizaciones'), ('ver_usuarios', 'Ver Usuarios')], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
