# Generated by Django 4.2 on 2023-04-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(max_length=70),
        ),
    ]
