# Generated by Django 4.2 on 2023-04-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_cliente_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='calle_numero_colonia',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
    ]
