# Generated by Django 4.2 on 2023-04-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_cliente_calle_numero_colonia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='condiciones',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='notas_especiales',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='notas_internas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='ajuste',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='condicion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='entrada_nominal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='notas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='prueba',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_mantenimiento',
            field=models.CharField(max_length=100),
        ),
    ]
