# Generated by Django 4.2 on 2023-04-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_cotizacion_codigo_alter_cotizacion_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='notas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
