# Generated by Django 4.2 on 2023-04-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_servicio_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo_mantenimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
