# Generated by Django 4.2 on 2023-04-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_servicio_tipo_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(max_length=150),
        ),
    ]
