# Generated by Django 4.2 on 2023-04-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_empleado_departamento_alter_empleado_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='notas_especiales',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
