# Generated by Django 4.2 on 2023-04-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_cotizacion_notas_especiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='notas_internas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
