# Generated by Django 4.2 on 2023-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_cotizacion_notas_internas'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='valor_ajuste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
