# Generated by Django 4.2.5 on 2023-10-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_rename_id_product_ordentrabajo_id_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='estatus',
        ),
    ]
