# Generated by Django 4.2.5 on 2023-10-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_remove_cotizacion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estatus',
            field=models.CharField(choices=[('vigente', 'vigente'), ('aceptada', 'aceptada'), ('rechazada', 'rechazada')], default='vigente', max_length=255),
        ),
    ]
