# Generated by Django 4.2.5 on 2023-10-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_cotizacion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('ACEPTADA', 'aceptada'), ('RECHAZADA', 'rechazada')], default='vigente', max_length=255),
        ),
    ]
