# Generated by Django 4.2.5 on 2023-10-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_cotizacion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='comentarioRechazo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
