# Generated by Django 4.2.3 on 2023-10-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_cotizacion_comentariorechazo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordentrabajo',
            old_name='id_Products',
            new_name='id_Product',
        ),
    ]
