# Generated by Django 4.2.5 on 2023-10-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_rename_id_products_ordentrabajo_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='comentarioRechazo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estatus',
            field=models.CharField(choices=[('VIGENTE', 'vigente'), ('ACEPTADA', 'aceptada'), ('RECHAZADA', 'rechazada')], default='VIGENTE', max_length=255),
        ),
    ]
