# Generated by Django 4.2.5 on 2023-11-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_ordentrabajo_comentariorechazo_ordentrabajo_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
