# Generated by Django 4.2.5 on 2023-11-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_ordentrabajo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estatus',
            field=models.CharField(choices=[('ESPERA', 'ESPERA'), ('LABORATORIO', 'LABORATORIO'), ('REVISION', 'REVISION'), ('TERMINADO', 'TERMINADO'), ('PAUSA', 'PAUSA')], default='ESPERA', max_length=255),
        ),
    ]
